gh_pr_view_json_commits.yml

diff --git a/.github/workflows/head_ref.yml b/.github/workflows/head_ref.yml
--- a/.github/workflows/head_ref.yml
+++ b/.github/workflows/head_ref.yml
@@ -25,11 +25,17 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       - run: |
           echo "gh pr view ${{ github.event.pull_request.head.ref }} --json commits | jq '.commits[] | .messageHeadline' ":
-          gh pr view ${{ github.event.pull_request.head.ref }} --json commits | jq '.commits[] | .messageHeadline' || true
+#          gh pr view ${{ github.event.pull_request.head.ref }} --json commits | jq '.commits[] | .messageHeadline' || true
           LIST_MESSAGE_COMMITS=$(gh pr view ${{ github.event.pull_request.head.ref }} --json commits | jq -r '.commits[] | .messageHeadline')
           for MESSAGE_COMMITS in "${LIST_MESSAGE_COMMITS}"
           do
               echo "${MESSAGE_COMMITS}"
+              if [[ "${MESSAGE_COMMITS}" =~ ^(feat|fix)\((alerts|cicd|dns|git|github|gke|gsuite|iam|inventory|tf)\):\s.*(DEVOPS-[0-9]+) ]]; then
+              echo "Valid message commits"
+              else
+              echo "Invalid message commits"
+              exit 1
+              fi
           done
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
